name: flutter_email_sender
description: Allows send emails from flutter using native platform functionality.
version: 3.0.1
author: Tautvydas Å idlauskas <tautvydas.sidlauskas@gmail.com>
homepage: https://github.com/sidlatau/flutter_email_sender

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.sidlatau.flutteremailsender
    pluginClass: FlutterEmailSenderPlugin

environment:
  sdk: ">=2.6.0 <3.0.0"
